@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Model as ModelPackage <<Rectangle>> {
  Class "<<interface>>\nReadOnlyJobFestGo" as ReadOnlyJobFestGo
  Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
  Class "<<interface>>\nModel" as Model
  Class JobFestGo
  Class ModelManager
  Class UserPrefs

  Class UniqueContactList
  Class UniqueTagList
  Class UniqueEventList
  Class UniqueTaskList
  Class Task
  Class Event
  Class Contact
  Class Tag
  Class I #FFFFFF

  hide circle
    UniqueTaskList -[hidden]> I
    UniqueEventList -[hidden]> I
    UniqueContactList -[hidden]> I
    UniqueTagList -[hidden]> I
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

JobFestGo .up.|> ReadOnlyJobFestGo

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyJobFestGo
ModelManager --> "1" JobFestGo
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

JobFestGo *--> "1" UniqueTaskList
JobFestGo *--> "1" UniqueContactList
JobFestGo *--> "1" UniqueEventList
JobFestGo *--> "1" UniqueTagList
UniqueEventList --> "~* all" Event
UniqueTaskList --> "~* all" Task
UniqueContactList --> "~* all" Contact
UniqueTagList --> "~* all" Tag
Contact -> "0..*" Tag
Event -down> "0..*" Contact
Event "1" <-left-> "0..*" Task


ModelManager -> "~* filtered" Contact
ModelManager -> "~* filtered" Event
ModelManager -> "~* filtered" Tag
ModelManager -> "~* filtered" Task

@enduml
