@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class EventContactDisplay
Class XYListPanel
Class XYCard
Class TagListPanel
Class TagCard
Class ABListPanel
Class ABCard
Class StatusBarFooter
Class CommandBox
}

note "XY = Event, Contact" as N1
note "AB = Task, Reminder" as N2

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" EventContactDisplay
MainWindow *-down-> "1" XYListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" TagListPanel
MainWindow --> "0..1" HelpWindow

EventContactDisplay -down-> "1" XYListPanel
EventContactDisplay -down-> "1" ABListPanel

XYListPanel -down-> "*" XYCard
TagListPanel -down-> "*" TagCard
ABListPanel -down-> "*" ABCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
EventContactDisplay --|> UiPart
CommandBox --|> UiPart
XYListPanel --|> UiPart
XYCard --|> UiPart
TagListPanel --|> UiPart
TagCard --|> UiPart
ABListPanel --|> UiPart
ABCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

XYCard ..> Model
TagCard ..> Model
ABCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

XYListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
