@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class EventContactDisplay
Class ContactListPanel
Class ContactCard
Class TagListPanel
Class TagCard
Class EventListPanel
Class EventCard
Class TaskListPanel
Class TaskCard
Class StatusBarFooter
Class CommandBox
Class ReminderListPanel
Class ReminderCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" EventContactDisplay
MainWindow *-down-> "1" ContactListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" TagListPanel
MainWindow *-down-> "1" ReminderListPanel
MainWindow *-down-> "1" EventListPanel
MainWindow --> "0..1" HelpWindow

EventContactDisplay -down-> "1" ContactListPanel
EventContactDisplay -down-> "1" EventListPanel
EventContactDisplay -down-> "1" TaskListPanel

ContactListPanel -down-> "*" ContactCard
TagListPanel -down-> "*" TagCard
EventListPanel -down-> "*" EventCard
TaskListPanel -down-> "*" TaskCard
ReminderListPanel -down-> "*" ReminderCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
EventContactDisplay --|> UiPart
CommandBox --|> UiPart
ContactListPanel --|> UiPart
ContactCard --|> UiPart
TagListPanel --|> UiPart
EventListPanel --|> UiPart
TaskListPanel --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

ContactCard ..> Model
TagCard ..> Model
EventCard ..> Model
TaskCard ..> Model
ReminderCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ContactListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
